name: Build
on: push
jobs:
  Debug:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build --configuration Debug
    - name: Test
      run: dotnet test
  Release:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test
